"""
Exporters for schema to SQL, DBML, Markdown, and JSON.
"""
import json
from models import SchemaResponse, TableInfo

def export_json(schema: SchemaResponse) -> str:
    return schema.model_dump_json(indent=2)

def export_markdown(schema: SchemaResponse) -> str:
    lines = [f"# Database Schema: {schema.database}\n"]
    
    lines.append("## Tables / Collections\n")
    for t in schema.tables:
        lines.append(f"### Table: `{t.name}` ({t.table_type})")
        lines.append("| Column | Type | PK | Nullable | Default |")
        lines.append("|---|---|---|---|---|")
        for c in t.columns:
            pk_str = "YES" if c.is_pk else "NO"
            null_str = "YES" if c.is_nullable else "NO"
            def_str = c.default if c.default is not None else ""
            lines.append(f"| {c.name} | {c.data_type} | {pk_str} | {null_str} | {def_str} |")
        lines.append("")
        
        if t.foreign_keys:
            lines.append("**Foreign Keys:**")
            for fk in t.foreign_keys:
                lines.append(f"- `{fk.constrained_column}` -> `{fk.referred_table}({fk.referred_column})`")
            lines.append("")
            
    if schema.inferred_relations:
        lines.append("## Inferred Relationships (NoSQL / Dynamic)\n")
        lines.append("| Source Table | Field | Target Table | Target Field | Confidence |")
        lines.append("|---|---|---|---|---|")
        for rel in schema.inferred_relations:
            lines.append(f"| {rel['from_table']} | {rel['from_field']} | {rel['to_table']} | {rel['to_field']} | {rel['confidence']} |")
        lines.append("")
        
    return "\n".join(lines)

def export_dbml(schema: SchemaResponse) -> str:
    lines = [f"// Database: {schema.database}\n// Generated by Schema Visualizer\n"]
    
    for t in schema.tables:
        lines.append(f"Table {t.name} {{")
        for c in t.columns:
            opts = []
            if c.is_pk:
                opts.append("primary key")
            if not c.is_nullable:
                opts.append("not null")
            if c.default:
                opts.append(f"default: `{c.default}`")
            
            opt_str = f" [{', '.join(opts)}]" if opts else ""
            lines.append(f"  {c.name} {c.data_type}{opt_str}")
        lines.append("}\n")
        
    # Explicit Foreign Keys
    for t in schema.tables:
        for fk in t.foreign_keys:
            lines.append(f"Ref: {t.name}.{fk.constrained_column} > {fk.referred_table}.{fk.referred_column}")
            
    # Inferred Relations
    for rel in schema.inferred_relations:
        lines.append(f"// Inferred Ref: {rel['from_table']}.{rel['from_field']} > {rel['to_table']}.{rel['to_field']} [confidence: {rel['confidence']}]")
        lines.append(f"Ref: {rel['from_table']}.{rel['from_field']} > {rel['to_table']}.{rel['to_field']}")

    return "\n".join(lines)

def export_sql(schema: SchemaResponse) -> str:
    lines = [f"-- Database DDL: {schema.database}\n"]
    
    for t in schema.tables:
        lines.append(f"CREATE TABLE `{t.name}` (")
        col_defs = []
        pks = []
        for c in t.columns:
            cdef = f"  `{c.name}` {c.data_type}"
            if not c.is_nullable:
                cdef += " NOT NULL"
            else:
                cdef += " NULL"
            if c.default is not None:
                cdef += f" DEFAULT {c.default}"
            if c.is_pk:
                pks.append(c.name)
            col_defs.append(cdef)
            
        if pks:
            col_defs.append(f"  PRIMARY KEY (`{'`, `'.join(pks)}`)")
            
        lines.append(",\n".join(col_defs))
        lines.append(");\n")
        
    for t in schema.tables:
        for fk in t.foreign_keys:
            fk_name = fk.name or f"fk_{t.name}_{fk.constrained_column}"
            lines.append(f"ALTER TABLE `{t.name}` ADD CONSTRAINT `{fk_name}` FOREIGN KEY (`{fk.constrained_column}`) REFERENCES `{fk.referred_table}`(`{fk.referred_column}`);")
            
    return "\n".join(lines)
